
import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    safe: {
        flex: 1,
        backgroundColor: '#5A1236',
    },
    confirmText: {
        fontSize: 32,
        fontWeight: 'bold',
        color: '#5A1236',
        textAlign: 'center',
        marginBottom: 30,
        marginTop: 40,
    },
    container: {
        flex: 1,
        justifyContent: 'center',
        padding: 20,
    },
    ScrollContainer: {
        flex: 1,
        justifyContent: 'center',
        padding: 5,
        width: '100%',
    },
    cornerImage: {
        position: 'absolute',
        marginTop: 25,
        width: 75,
        height: 75,
        borderRadius: 12,
        top: 18,
        zIndex: 10,
    },
    dropdownList2: {
        backgroundColor: '#f9f9f9',
        borderWidth: 1,
        borderColor: '#ddd',
        borderRadius: 8,
        marginTop: -5,
        marginBottom: 15,
        maxHeight: 400,
    },
    topLeft: {
        left: 10,
    },
    topRight: {
        right: 10,
    },
    card: {
        backgroundColor: '#ffffff',
        borderRadius: 14,
        padding: 20,
        shadowColor: '#000',
        shadowOpacity: 0.12,
        shadowOffset: { width: 0, height: 6 },
        shadowRadius: 12,
        elevation: 6,
    },
    title: {
        fontSize: 20,
        fontWeight: '600',
        marginBottom: 12,
        color: '#111',
    },
    label: {
        fontSize: 13,
        color: '#555',
        marginTop: 8,
        marginBottom: 6,
    },
    input: {
        backgroundColor: '#fff',
        borderWidth: 1,
        borderColor: '#eee',
        paddingVertical: 10,
        paddingHorizontal: 12,
        borderRadius: 10,
        fontSize: 15,
        color: '#111',
        maxHeight: 60,
    },
    button: {
        marginTop: 14,
        backgroundColor: '#5A1236',
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 10,
        alignItems: 'center',
    },
    button2: {
        position: 'absolute',
        bottom: 50,
        marginTop: 14,
        backgroundColor: '#5A1236',
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 10,
        alignItems: 'center',
    },
    buttonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
    error: {
        color: '#b91c1c',
        marginTop: 8,
    },
    loggedInContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
        marginTop: 25,
        backgroundColor: '#ffffff',
    },
    loggedInContainer2: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
        backgroundColor: '#ffffff',
    },
    superiorPanel: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        height: 130,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        backgroundColor: '#5A1236',
        zIndex: 10,
    },
    welcomeText: {
        fontSize: 28,
        fontWeight: '600',
        marginTop: 10,
        marginBottom: 0,
        color: '#111',
    },
    welcomeText2: {
        position: 'absolute',
        top: 150,
        fontSize: 32,
        fontWeight: '600',
        marginTop: 10,
        marginBottom: 0,
        color: '#111',
    },
    optionButton: {
        backgroundColor: '#D9D9D9',
        paddingVertical: 10,
        width: '60%',
        borderRadius: 25,
        alignItems: 'center',
        marginVertical: 5,
    },
    optionText: {
        color: '#000000',
        fontSize: 20,
        fontWeight: '700',
    },
    tableContainer: {
        width: '100%',
    },
    tableRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 12,
        paddingHorizontal: 15,
        backgroundColor: '#d9d9d9',
    },
    tableAlt: {
        backgroundColor: '#c8c8c8',
    },
    tableHeader: {
        backgroundColor: '#5A1236',
        paddingVertical: 14,
    },
    tableText: {
        color: 'black',
        flex: 1,
        textAlign: 'center',
    },
    tableWrapper: {
        width: '90%',
        marginTop: 20,
        borderRadius: 12,
        backgroundColor: '#ffffff20',
        overflow: 'hidden',
        maxHeight: 380,
        alignSelf: 'center',
        borderWidth: 1,
        borderColor: '#a1a1a1',
    },

    tableScroll: {
        width: '100%',
    },

    tableContent: {
        paddingBottom: 10,
    },
    headerText: {
        color: 'white',
        fontWeight: 'bold',
    },
    statusCell: {
        flex: 1,
        alignItems: 'center',
    },
    statusDot: {
        width: 12,
        height: 12,
        borderRadius: 6,
    },
    formCard2: {
        width: '90%',
        backgroundColor: '#F5F5F5',
        borderRadius: 16,
        paddingVertical: 25,
        paddingHorizontal: 20,
        borderWidth: 1,
        borderColor: '#D9D9D9',
        marginBottom: 20,
        marginTop: 5,
        maxHeight: 550,
    },
    formCardScroll: {
        maxHeight: 500,
    },
    label2: {
        fontSize: 14,
        fontWeight: '700',
        color: '#000',
        marginBottom: 6,
        marginTop: 10,
    },
    input2: {
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: '#D9D9D9',
        borderRadius: 20,
        paddingVertical: 10,
        paddingHorizontal: 15,
        fontSize: 15,
        marginBottom: 15,
    },
    superiorTitle: {
        marginTop: 40,
        color: 'white',
        fontSize: 24,
        fontWeight: 'bold',
        textAlign: 'center',
        flex: 1,
    },
    errorImage: {
        width: 150,
        height: 150,
        marginVertical: 20,
    },
    infoText: {
        fontSize: 18,
        color: '#b91c1c',
        marginTop: 8,
        marginBottom: 6,
    },
    informeContainer: {
        flex: 1,
        paddingTop: 150,
        backgroundColor: '#ffffff',
    },
    informeScrollView: {
        flex: 1,
        paddingBottom: 120,
    },
    informeCard: {
        width: '90%',
        backgroundColor: '#F5F5F5',
        borderRadius: 16,
        paddingVertical: 25,
        paddingHorizontal: 20,
        borderWidth: 1,
        borderColor: '#D9D9D9',
        marginBottom: 20,
        marginTop: 5,
        alignSelf: 'center',
    },
    informeSection: {
        marginBottom: 20,
    },
    informeRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 10,
    },
    informeColumnItem: {
        alignItems: 'center',
    },
    informeReporteCard: {
        backgroundColor: '#f9f9f9',
        padding: 10,
        marginBottom: 10,
        borderRadius: 5,
    },
    informeStatsBox: {
        backgroundColor: '#f5f5f5',
        padding: 15,
        borderRadius: 10,
        marginBottom: 15,
    },
    informeEmptyText: {
        textAlign: 'center',
        marginTop: 20,
        color: '#999',
    },
    informeReportList: {
        marginBottom: 15,
        borderRadius: 8,
        overflow: 'hidden',
    },
    informeReportListItem: {
        backgroundColor: '#f0f0f0',
        paddingVertical: 12,
        paddingHorizontal: 15,
        borderBottomWidth: 1,
        borderBottomColor: '#ddd',
    },
    informeReportListItemSelected: {
        backgroundColor: '#0066cc',
    },
    informeReportListText: {
        fontSize: 14,
        color: '#333',
    },
    informeReportListTextSelected: {
        color: '#fff',
        fontWeight: 'bold',
    },
    dropdownList: {
        backgroundColor: '#f9f9f9',
        borderWidth: 1,
        borderColor: '#ddd',
        borderRadius: 8,
        marginTop: -5,
        marginBottom: 15,
        maxHeight: 200,
        overflow: 'hidden',
    },
    dropdownItem: {
        paddingVertical: 12,
        paddingHorizontal: 15,
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
    },
});
