import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    safe: {
        flex: 1,
        backgroundColor: '#5A1236',
    },
    container: {
        flex: 1,
        justifyContent: 'center',
        padding: 20,
    },
    cornerImage: {
        position: 'absolute',
        marginTop: 25,
        width: 75,
        height: 75,
        borderRadius: 12,
        top: 18,
        zIndex: 10,
    },
    topLeft: {
        left: 10,
    },
    topRight: {
        right: 10,
    },
    card: {
        backgroundColor: '#ffffff',
        borderRadius: 14,
        padding: 20,
        shadowColor: '#000',
        shadowOpacity: 0.12,
        shadowOffset: { width: 0, height: 6 },
        shadowRadius: 12,
        elevation: 6,
    },
    title: {
        fontSize: 20,
        fontWeight: '600',
        marginBottom: 12,
        color: '#111',
    },
    label: {
        fontSize: 13,
        color: '#555',
        marginTop: 8,
        marginBottom: 6,
    },
    input: {
        backgroundColor: '#fff',
        borderWidth: 1,
        borderColor: '#eee',
        paddingVertical: 10,
        paddingHorizontal: 12,
        borderRadius: 10,
        fontSize: 15,
        color: '#111',
    },
    button: {
        marginTop: 14,
        backgroundColor: '#5A1236',
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 10,
        alignItems: 'center',
    },
    button2: {
        position: 'absolute',
        bottom: 50,
        marginTop: 14,
        backgroundColor: '#5A1236',
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 10,
        alignItems: 'center',
    },
    buttonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
    error: {
        color: '#b91c1c',
        marginTop: 8,
    },
    loggedInContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
        marginTop: 25,
        backgroundColor: '#ffffff',
    },
    loggedInContainer2: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
        backgroundColor: '#ffffff',
    },
    superiorPanel: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        height: 130,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        backgroundColor: '#5A1236',
        zIndex: 10,
    },
    welcomeText: {
        fontSize: 28,
        fontWeight: '600',
        marginBottom: 25,
        color: '#111',
    },
    optionButton: {
        backgroundColor: '#D9D9D9',
        paddingVertical: 10,
        width: '60%',
        borderRadius: 10,
        alignItems: 'center',
        marginVertical: 8,
    },
    optionText: {
        color: '#000000',
        fontSize: 20,
        fontWeight: '700',
    },
    tableContainer: {
        width: '90%',
        marginTop: 20,
        borderRadius: 10,
        overflow: 'hidden',
    },
    tableRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 10,
        paddingHorizontal: 15,
        backgroundColor: '#d9d9d9',
    },
    tableAlt: {
        backgroundColor: '#bfbfbf',
    },
    tableHeader: {
        backgroundColor: '#5A1236',
    },
    tableText: {
        color: 'black',
        flex: 1,
        textAlign: 'center',
    },
    headerText: {
        color: 'white',
        fontWeight: 'bold',
    },
    statusCell: {
        flex: 1,
        alignItems: 'center',
    },
    statusDot: {
        width: 12,
        height: 12,
        borderRadius: 6,
    },
    formCard2: {
        width: '90%',
        backgroundColor: '#F8F8F8',
        borderRadius: 16,
        paddingVertical: 25,
        paddingHorizontal: 20,
        borderWidth: 1,
        borderColor: '#D9D9D9',
        marginBottom: 20,
    },

    label2: {
        fontSize: 14,
        fontWeight: '700',
        color: '#000',
        marginBottom: 6,
        marginTop: 10,
    },

    input2: {
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: '#D9D9D9',
        borderRadius: 20,
        paddingVertical: 10,
        paddingHorizontal: 15,
        fontSize: 15,
        marginBottom: 15,
    },
    superiorTitle: {
        marginTop: 40,
        color: 'white',
        fontSize: 24,
        fontWeight: 'bold',
        textAlign: 'center',
        flex: 1,
    },
});
